### ISSUE TITLE
"incompatible library version"

### ISSUE THREAD

**Issue by sj26** [tpope/rbenv-communal-gems#13]
I have ruby 2.6.5 and 2.6.6 installed with communized gems. I have noticed I'm getting errors like:

```
Traceback (most recent call last):
...
.../lib/active_support/dependencies.rb:324:in `require': incompatible library version - .../redcarpet-3.5.0/lib/redcarpet.bundle (LoadError)
```

Has anyone else been having this trouble? I know it's not caused by this plugin, just wondering if other users are having the same trouble and if the plugin might not work for future versions.

**Comment by tpope** [comment]
Can confirm, Ruby 2.6 has given me so many problems that I ended up disabling communize-gems entirely.

**Comment by sj26** [comment]
> ended up disabling communize-gems entirely

Yeah, I did the same 😞
